{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hermetiq-core.serviceAccountName" . }}
  namespace: {{ include "hermetiq-core.namespace" . }}
  labels:
    {{- include "hermetiq-core.labels" . | nindent 4 }}
    {{- if .Values.azureWorkloadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.serviceAccount.annotations .Values.azureWorkloadIdentity.enabled .Values.gcpWorkloadIdentity.enabled }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- include "hermetiq-core.commonAnnotations" $ | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- include "hermetiq-core.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.azureWorkloadIdentity.enabled }}
    azure.workload.identity/client-id: {{ required "azureWorkloadIdentity.clientId is required when azureWorkloadIdentity.enabled=true" .Values.azureWorkloadIdentity.clientId | quote }}
    {{- end }}
    {{- if .Values.gcpWorkloadIdentity.enabled }}
    iam.gke.io/gcp-service-account: {{ required "gcpWorkloadIdentity.serviceAccount is required when gcpWorkloadIdentity.enabled=true" .Values.gcpWorkloadIdentity.serviceAccount | quote }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
