{{- if .Values.victoriaMetrics.natsPodScrape.enabled }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ .Values.victoriaMetrics.natsPodScrape.name }}
  namespace: {{ include "hermetiq-core.namespace" . }}
  labels:
    {{- include "hermetiq-core.labels" . | nindent 4 }}
    {{- include "hermetiq-core.componentLabel" (dict "component" "nats") | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ include "hermetiq-core.namespace" . }}
  podMetricsEndpoints:
    - port: {{ .Values.victoriaMetrics.natsPodScrape.port }}
  selector:
    matchLabels:
      {{- include "hermetiq-core.tplvalues.render" (dict "value" .Values.victoriaMetrics.natsPodScrape.selectorLabels "context" .) | nindent 6 }}
{{- end }}
