apiVersion: v2
name: bb-worker-operator
description: Buildbarn worker pool operator for Kubernetes
type: application
version: 0.3.1
appVersion: "v0.3.1"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
keywords:
  - buildbarn
  - bazel
  - remote-execution
  - operator
  - kubebuilder
maintainers:
  - name: Hermetiq
