{
 "title": "BB gRPC servers",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, namespace)"
    }
   },
   {
    "name": "grpc_service",
    "label": "gRPC service name",
    "query": {
     "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\"}, grpc_service)"
    }
   },
   {
    "name": "grpc_method",
    "label": "gRPC method name",
    "query": {
     "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\"}, grpc_method)"
    }
   },
   {
    "name": "grpc_code",
    "label": "gRPC status code",
    "query": {
     "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\"}, grpc_code)"
    }
   },
   {
    "name": "kubernetes_service",
    "label": "Kubernetes service name",
    "query": {
     "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\"}, kubernetes_service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Number of in-flight operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_in_flight:sum{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_in_flight:sum{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Operation rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\",grpc_code=~\"$grpc_code\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By gRPC status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\",grpc_code=~\"$grpc_code\",grpc_code=~\"$grpc_code\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{namespace=\"$namespace\",grpc_code=~\"$grpc_code\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Messages sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_sent:irate1m{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_sent:irate1m{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Messages received", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_received:irate1m{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_received:irate1m{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "RPC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service_le:grpc_server_handling_seconds_bucket:irate1m{namespace=\"$namespace\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\"}) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}