{
 "title": "BB Scheduler",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, namespace)"
    }
   },
   {
    "name": "instance_name_prefix",
    "label": "Instance name",
    "query": {
     "query": "label_values(instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued:irate1m{namespace=\"$namespace\"}, instance_name_prefix)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Task rate by stage transition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nonexistent → Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ninstance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}}"
    }
   ]
  },
  {
   "title": "Queued → Executing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ninstance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}}"
    }
   ]
  },
  {
   "title": "Executing → Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ngrpc_code_instance_name_prefix_platform_result_size_class:buildbarn_builder_in_memory_build_queue_tasks_completed:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}} {{result}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Completed → Removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ninstance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_removed:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}}"
    }
   ]
  },
  { "title": "Task count by stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Queued",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ninstance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued:sum{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}}"
    }
   ]
  },
  {
   "title": "Executing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ninstance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing:sum{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(label_replace(label_replace(\ninstance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_completed:sum{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}\n,\"platform\",\"$1=$3$4\",\"platform\",'{\"properties\":\\\\[{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)]}')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')\n,\"platform\",\"$1 $2=$4$5\",\"platform\",'(.*),{\"name\":\"([^\"]*)\"(,\"value\":\"([^\"]*)\")?}(.*)')",
     "legendFormat": "{{instance_name_prefix}} [{{platform}}] {{size_class}}"
    }
   ]
  },
  { "title": "Task duration by stage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Queued",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued_duration_seconds_bucket:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Executing",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum(instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing_duration_seconds_bucket:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum(instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_completed_duration_seconds_bucket:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Task execution retries",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing_retries_bucket:irate1m{namespace=\"$namespace\",instance_name_prefix=~\"$instance_name_prefix\"}) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}