{
 "title": "BB Storage",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Per-replica worst shard retention: whether it is safe to restart the other replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "ac",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "{{kubernetes_replica}}"
    }
   ]
  },
  {
   "title": "cas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "{{kubernetes_replica}}"
    }
   ]
  },
  {
   "title": "Per-shard best replica retention: amount of data accessible right now",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "ac",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "cas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "Per-shard worst replica retention: amount of data to remain accessible if a replica were to crash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "ac",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "cas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  { "title": "Key-location map: Get()", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "ac operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "TooManyAttempts"
    }
   ]
  },
  {
   "title": "cas operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "TooManyAttempts"
    }
   ]
  },
  {
   "title": "ac operation attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m{namespace=\"$namespace\",storage_type=\"ac\"} > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "cas operation attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m{namespace=\"$namespace\",storage_type=\"cas\"} > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Key-location map: Put()", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "ac operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_ignored_invalid:irate1m{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "IgnoredInvalid"
    },
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m{namespace=\"$namespace\",storage_type=\"ac\"}",
     "legendFormat": "TooManyIterations"
    }
   ]
  },
  {
   "title": "cas operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_ignored_invalid:irate1m{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "IgnoredInvalid"
    },
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m{namespace=\"$namespace\",storage_type=\"cas\"}",
     "legendFormat": "TooManyIterations"
    }
   ]
  },
  {
   "title": "ac operation iterations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m{namespace=\"$namespace\",storage_type=\"ac\"} > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "cas operation iterations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m{namespace=\"$namespace\",storage_type=\"cas\"} > 0",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}