{
 "title": "NATS JetStream",
 "description": "NATS JetStream Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": { "query": "label_values(server_id)" } },
   { "name": "stream", "label": "Stream", "query": { "query": "label_values(stream_name)" } },
   { "name": "consumer", "label": "Consumer", "query": { "query": "label_values(consumer_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Message Rate per Second (by Project)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(hermetiq_publish_total{status=\"success\"}[5m])) by (project)",
     "legendFormat": "{{project}} {{subject}}"
    }
   ]
  },
  {
   "title": "Messages Published per Minute (by Project)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(hermetiq_publish_total{status=\"success\"}[1m])) by (project)",
     "legendFormat": "{{project}} {{subject}}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{server_id=~\"$server\"})/sum(nats_varz_jetstream_config_max_storage{server_id=~\"$server\"})"
    },
    {}
   ]
  },
  {
   "title": "Total Storage Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{server_id=~\"$server\"})/sum(nats_varz_jetstream_config_max_memory{server_id=~\"$server\"})"
    },
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Max Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_storage{server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_config_max_memory{server_id=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_server_total_consumers{server_id=~\"$server\"})"
    }
   ]
  },
  { "title": "Stream metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_bytes{stream_name=~\"BEP.*|PROGRESS.*\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_messages{stream_name=~\"BEP.*|PROGRESS.*\"}) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "Total delivered messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_delivered_consumer_seq{server_id=~\"$server\",stream_name=~\"BEP.*|PROGRESS.*\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Rate (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_stream_last_seq{server_id=~\"$server\",stream_name=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  { "title": "Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Messages per second (++/--)",
   "type": "timeseries",
   "description": "Messages added & processed per minute per consumer",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_num_pending{server_id=~\"$server\",stream_name=~\"BEP.*|PROGRESS.*\",consumer_name=~\"$consumer\"}[$__rate_interval])+rate(nats_consumer_delivered_consumer_seq{server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} +"
    },
    {
     "expr": "- sum(rate(nats_consumer_delivered_consumer_seq{server_id=~\"$server\",stream_name=~\"BEP.*|PROGRESS.*\",consumer_name=~\"$consumer\",consumer_name=~\"$consumer\"}[$__rate_interval])) by (consumer_name)",
     "legendFormat": "{{consumer_name}} -"
    }
   ]
  },
  {
   "title": "Queue Latency BEP_STREAM_0",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_queue_latency_bucket{stream=\"BEP_STREAM_0\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queue Latency BEP_STREAM_1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_queue_latency_bucket{stream=\"BEP_STREAM_1\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queue Latency BEP_STREAM_2",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_queue_latency_bucket{stream=\"BEP_STREAM_2\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queue Latency BEP_STREAM_3",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_queue_latency_bucket{stream=\"BEP_STREAM_3\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queue Latency BEP_STREAM_4",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 44 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_queue_latency_bucket{stream=\"BEP_STREAM_4\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Publish Duration (BEP PROD)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_publish_duration_seconds_bucket{\"service.name\"=\"hermetiq-prod\",subject=~\"bep_0.lifecycle.*|bep_0.build_tool.*|bep_1.lifecycle.*|bep_1.build_tool.*|bep_2.lifecycle.*|bep_2.build_tool.*|bep_3.lifecycle.*|bep_3.build_tool.*|bep_4.lifecycle.*|bep_4.build_tool.*\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Publish Duration (BEP Progress PROD)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_publish_duration_seconds_bucket{\"service.name\"=\"hermetiq-prod\",subject=~\"bep_0.progress.*|bep_1.progress.*|bep_2.progress.*|bep_3.progress.*|bep_4.progress.*\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Publish Batch Duration (Cache PROD)",
   "type": "heatmap",
   "description": "time to publish a batch of either 500 cache events or every 250ms",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_publish_duration_seconds_bucket{\"service.name\"=\"grpc-cache-proxy\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "p50 Message Latency",
   "type": "timeseries",
   "description": "p50 for time in queue",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (stream, le) (rate(hermetiq_bep_queue_latency_bucket{stream=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])))",
     "legendFormat": "{{rpc.method}}"
    }
   ]
  },
  {
   "title": "p95 Message Latency",
   "type": "timeseries",
   "description": "p95 for time in queue",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (stream, le) (rate(hermetiq_bep_queue_latency_bucket{stream=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])))",
     "legendFormat": "{{rpc.method}}"
    }
   ]
  },
  {
   "title": "p99 Message Latency",
   "type": "timeseries",
   "description": "p99 for time in queue",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (stream, le) (rate(hermetiq_bep_queue_latency_bucket{stream=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])))",
     "legendFormat": "{{rpc.method}}"
    }
   ]
  },
  {
   "title": "Process Latency BEP_STREAM_0",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_process_latency_bucket{stream=\"BEP_STREAM_0\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process Latency BEP_STREAM_1",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 68 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_process_latency_bucket{stream=\"BEP_STREAM_1\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process Latency BEP_STREAM_2",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 68 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_process_latency_bucket{stream=\"BEP_STREAM_2\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process Latency BEP_STREAM_3",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 68 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_process_latency_bucket{stream=\"BEP_STREAM_3\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process Latency BEP_STREAM_4",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 68 },
   "targets": [
    {
     "expr": "sum(irate(hermetiq_bep_process_latency_bucket{stream=\"BEP_STREAM_4\"}[1m])) by (le) > 0",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "p50 Process Latency",
   "type": "timeseries",
   "description": "p50 for time to process event (includes write to DB)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (stream, le) (rate(hermetiq_bep_process_latency_bucket{stream=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])))",
     "legendFormat": "{{rpc.method}}"
    }
   ]
  },
  {
   "title": "p95 Process Latency",
   "type": "timeseries",
   "description": "p95 for time to process event (includes write to DB)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (stream, le) (rate(hermetiq_bep_process_latency_bucket{stream=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])))",
     "legendFormat": "{{rpc.method}}"
    }
   ]
  },
  {
   "title": "p99 Process Latency",
   "type": "timeseries",
   "description": "p99 for time to process event (includes write to DB)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (stream, le) (rate(hermetiq_bep_process_latency_bucket{stream=~\"BEP.*|PROGRESS.*\"}[$__rate_interval])))",
     "legendFormat": "{{rpc.method}}"
    }
   ]
  },
  {
   "title": "p50 Process Latency (by Bazel Type)",
   "type": "timeseries",
   "description": "p50 for time to process event (includes write to DB)",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (bazel_type, le) (rate(hermetiq_bep_process_latency_bucket[$__rate_interval])))",
     "legendFormat": "{{bazel_type}}"
    }
   ]
  },
  {
   "title": "p95 Process Latency (by Bazel Type)",
   "type": "timeseries",
   "description": "p95 for time to process event (includes write to DB)",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (bazel_type, le) (rate(hermetiq_bep_process_latency_bucket[$__rate_interval])))",
     "legendFormat": "{{bazel_type}}"
    }
   ]
  },
  {
   "title": "p99 Process Latency (by Bazel Type)",
   "type": "timeseries",
   "description": "p99 for time to process event (includes write to DB)",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (bazel_type, le) (rate(hermetiq_bep_process_latency_bucket[$__rate_interval])))",
     "legendFormat": "{{bazel_type}}"
    }
   ]
  },
  {
   "title": "Pending messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_pending{server_id=~\"$server\",stream_name=~\"BEP.*|PROGRESS.*\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Message Acks Pending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{server_id=~\"$server\",stream_name=~\"BEP.*|PROGRESS.*\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "{{consumer_name}}"
    }
   ]
  },
  {
   "title": "Redelivered Message Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_redelivered{server_id=~\"$server\",stream_name=~\"$stream\",consumer_name=~\"$consumer\"}) by (consumer_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}