apiVersion: v2
name: hermetiq
description: Hermetiq gRPC API, MCP server, publisher, subscriber, dashboard, and DB maintenance jobs
type: application
version: 0.9.0
appVersion: "0.9.0"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of Hermetiq chart
keywords:
  - hermetiq
  - MCP
  - nats
  - bazel BEP
  - build analytics
  - build engineer AI agent
maintainers:
  - name: Hermetiq
